### PR TITLE
OffsetTimeSerializer not writing seconds for time objects

### LINKED ISSUE #112: OffsetTimeSerializer not writing seconds for time objects
When having a OffsetTime field with e.g. 15:00:00Z and serializing this with Jackson it outputs 15:00Z and this is not a valid RFC 3339 time, so our validation fails (backend and front).

We need to add a custom serializer to address this problem.

See more in this isuue:
https://github.com/FasterXML/jackson-modules-java8/issues/299

### PR DESCRIPTION
**Pull request by 7eben**
Close #112

### CODE REVIEW

File: kuflow-temporal-worker/src/main/java/com/kuflow/temporal/worker/jackson/OffsetTimeSerializer.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+    }
+
+    public OffsetTimeSerializer(DateTimeFormatter formatter) {
+        super(OffsetTime.class);
+        this.formatter = formatter;
+    }
+
+    @Override
+    public void serialize(OffsetTime value, JsonGenerator gen, SerializerProvider provider) throws IOException {
+        if (value != null) {
```
Comment (jrpedrianes) [inline kuflow-temporal-worker/src/main/java/com/kuflow/temporal/worker/jackson/OffsetTimeSerializer.java:47]: Is this condition possible?

**Review by jrpedrianes — CHANGES_REQUESTED** [review]

File: kuflow-temporal-worker/src/main/java/com/kuflow/temporal/worker/jackson/OffsetTimeSerializer.java (hunk 1 above)
Comment (7eben) [reply kuflow-temporal-worker/src/main/java/com/kuflow/temporal/worker/jackson/OffsetTimeSerializer.java:47]: I don't know

Comment (jrpedrianes) [reply kuflow-temporal-worker/src/main/java/com/kuflow/temporal/worker/jackson/OffsetTimeSerializer.java:47]: looking into other implementations, ie, EnumSerializer, "value" never can be null.

Comment (7eben) [reply kuflow-temporal-worker/src/main/java/com/kuflow/temporal/worker/jackson/OffsetTimeSerializer.java:47]: I don't know if it will ever come to NULL, and it saves. I don't know if it has to do with INCLUDE_NON_NULL being enabled or not. But I prefer to leave the IF.

Comment (jrpedrianes) [reply kuflow-temporal-worker/src/main/java/com/kuflow/temporal/worker/jackson/OffsetTimeSerializer.java:47]: The javadoc said that value can't be null, so to avoid confusions,  I prefer to remove the condition:

    /**
     * Method that can be called to ask implementation to serialize
     * values of type this serializer handles.
     *
     * @param value Value to serialize; can <b>not</b> be null.
     * @param gen Generator used to output resulting Json content
     * @param serializers Provider that can be used to get serializers for
     *   serializing Objects value contains, if any.
     */
    public abstract void serialize(T value, JsonGenerator gen, SerializerProvider serializers)
        throws IOException;

**Review by jrpedrianes — APPROVED** [review]
